name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: docker compose pull

      - name: Set permissions for Laravel storage
        run: |
          chmod -R 0777 storage
          chmod -R 0777 bootstrap/cache

      - name: ğŸ» Install dependencies
        run: make composer-install

      - name: ğŸ³ Start all the environment
        run: make start

      - name: ğŸ”¦ Lint
        run: make lint

      - name: ğŸ Static analysis
        run: make static-analysis

      - name: ğŸ¤¢ Mess detector
        run: make mess-detector

      - name: ğŸ—ï¸ Architecture
        run: make test-architecture

      - name: ğŸ¦­ Wait for the database to get up
        run: |
          while ! make ping-mysql &>/dev/null; do
              echo "Waiting for database connection..."
              sleep 2
          done

      - name: ğŸ¬ Prepare the database
        run: make prepare-db

      - name: âœ… Run the tests
        run: make test
